Vagrant.configure("2") do |config|

    # libvirt
    config.vm.provider "libvirt" do |lv|
      lv.cpus = 8
      lv.memory = 8196
    end



  config.vm.define "arch" do |ds|
    ds.vm.hostname = "arch"
    ds.vm.box = "Zelec/manjarolinux"
    ds.vm.synced_folder "../common/", "/common/"
    ds.vm.network "private_network", ip: "192.168.10.10"  

    ds.vm.provision "shell", path: "./arch-post-install.sh", privileged: true
  end
end